kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
  namespace: u1-spark-cluster
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      volumes:
        - name: user1
          quobyte:
            registry: LBIP:7861
            volume: user1
            readOnly: false
            user: root
            group: root
      containers:
        - name: spark-master
          image: gcr.io/google_containers/spark:1.5.2_v1
          command: ["/start-master"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /user
              name: user1
