kind: ReplicationController
apiVersion: v1
metadata:
  name: zeppelin-controller
  namespace: u1-spark-cluster
spec:
  replicas: 1
  selector:
    component: zeppelin
  template:
    metadata:
      labels:
        component: zeppelin
    spec:
      volumes:
        - name: user1
          quobyte:
            registry: LBIP:7861
            volume: user1
            readOnly: false
            user: root
            group: root
      containers:
        - name: zeppelin
          image: gcr.io/google_containers/zeppelin:v0.5.6_v1
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /user
              name: user1
