kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  namespace: u2-spark-cluster
spec:
  replicas: 2
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      volumes:
        - name: user2-pvc
          persistentVolumeClaim:
            claimName: user2-pvc
      containers:
        - name: spark-worker
          image: gcr.io/google_containers/spark:1.5.2_v1
          command: ["/start-worker"]
          ports:
            - containerPort: 8081
          resources:
            requests:
              cpu: 100m
          volumeMounts:
            - mountPath: /user
              name: user2-pvc
